const banner = require('./banner')
const fornecedor = require('./Fornecedor')
const cliente = require('./cliente')
const fotosDoProduto = require('./fotosDoProduto')
const login = require('./login')
const logo = require('./logo')
const produto = require('./produto')
const { Pedido, detalhesDoPedido } = require('./pedido')
const Session = require('./session')

banner.sync({force:true})
fornecedor.sync({force:true})
cliente.sync({force:true})
fotosDoProduto.sync({force:true})
login.sync({force:true})
logo.sync({force:true})
produto.sync({force:true})
Pedido.sync({force:true})
detalhesDoPedido.sync({force:true})
// Session.sync({force:true})